### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by pchschulz** [tractorcow/silverstripe-colorpicker#22]
Very good module, but without a license I can't use it in business projects. So maybe BSD-3 license as recommended by [https://docs.silverstripe.org/en/4/developer_guides/extending/modules/#documentation-guidelines](https://docs.silverstripe.org/en/4/developer_guides/extending/modules/#documentation-guidelines)

**Comment by robbieaverill** [comment]
It may be tricky to license this, since it has been forked a few times and was originally a copy of someone else's work - see https://github.com/dimension27/silverstripe-colorpicker#history

**Comment by bummzack** [comment]
That's correct, the original module was written by me… problem is, that the module also contains JS code, that has no license…

**Comment by robbieaverill** [comment]
[The jQuery plugin's website](https://www.eyecon.ro/colorpicker/) says it's licensed under dual MIT and GPL licenses. I'm no expert in licensing rules, but I think that provided this module retains the original license on the thirdparty code, and @bummzack provides his permission to either license this under his name or under @tractorcow's name, then it should be feasible to add a license to this module.

**Comment by bummzack** [comment]
I'm fine with MIT… but I'll leave the final say to @tractorcow, since he's the maintainer here ;)

**Comment by tractorcow** [comment]
I guess we could copy the JS license (mit / gpl) for the JS, and add a specific bsd-3-clause for the php code.

**Comment by tractorcow** [comment]
Added at https://github.com/tractorcow/silverstripe-colorpicker/blob/master/LICENSE.md

@bummzack happy to adjust wording if you want me to put your name on it too.
